---
core:
    num_workers: 50


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Nornir-Nuggets/hosts.yaml"
        group_file: "/home/ipvzero/Nornir-Nuggets/groups.yaml"
        defaults_file: "/home/ipvzero/Nornir-Nuggets/defaults.yaml"
